DROP TABLE IF EXISTS `hibernate_sequences`;
CREATE TABLE `hibernate_sequences` (
  `sequence_name` varchar(255) NOT NULL,
  `next_val` bigint DEFAULT NULL,
  PRIMARY KEY (`sequence_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `TRANSACTION_TBL`;
CREATE TABLE `TRANSACTION_TBL` (
  `TXN_ID` int NOT NULL,
  `PAYMENT_MODE` smallint DEFAULT NULL,
  `TRANSACTION_AMOUNT` int DEFAULT NULL,
  `TXN_DATE_TIME` datetime(6) DEFAULT NULL,
  `TXN_TYPE` smallint DEFAULT NULL,
  `FROM_USER` varchar(60) DEFAULT NULL,
  `TO_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`TXN_ID`),
  KEY `FKjrtd2gi6yv500hmj7pv4aaeln` (`FROM_USER`),
  KEY `FKay9t5n2awg8btgdgakbhyxajg` (`TO_USER`),
  CONSTRAINT `FKay9t5n2awg8btgdgakbhyxajg` FOREIGN KEY (`TO_USER`) REFERENCES `USER_TBL` (`USER_ID`),
  CONSTRAINT `FKjrtd2gi6yv500hmj7pv4aaeln` FOREIGN KEY (`FROM_USER`) REFERENCES `USER_TBL` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `USER_TBL`;
CREATE TABLE `USER_TBL` (
  `USER_ID` varchar(60) NOT NULL,
  `DOB` date DEFAULT NULL,
  `ADDRESS` varchar(120) DEFAULT NULL,
  `CITY` varchar(40) DEFAULT NULL,
  `COUNTRY` varchar(40) DEFAULT NULL,
  `CREATION_DATE` datetime(6) DEFAULT NULL,
  `EXPIRY_DATE` date DEFAULT NULL,
  `FIRST_NAME` varchar(40) DEFAULT NULL,
  `LAST_NAME` varchar(40) DEFAULT NULL,
  `LAST_UPDATED_DATE` datetime(6) DEFAULT NULL,
  `PASSWORD` varchar(40) DEFAULT NULL,
  `PHONE` varchar(15) DEFAULT NULL,
  `STATE` varchar(40) DEFAULT NULL,
  `WALLET_BALANCE` int DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;